In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/train.csv')
df.head()

id  Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0   0               0.0         No                      6.0            4.0   
1   1               1.0         No                      7.0            3.0   
2   2               6.0        Yes                      1.0            0.0   
3   3               3.0         No                      7.0            3.0   
4   4               1.0         No                      4.0            4.0   

  Drained_after_socializing  Friends_circle_size  Post_frequency Personality  
0                        No                 15.0             5.0   Extrovert  
1                        No                 10.0             8.0   Extrovert  
2                       NaN                  3.0             0.0   Introvert  
3                        No                 11.0             5.0   Extrovert  
4                        No                 13.0             NaN   Extrovert

In [36]:
import numpy as np
np.linspace(0, 1, 10)
np.arange(1,21,2)
np.eye(3)
np.random.rand(2,3)
arr = np.random.randint(1,21, (5,5))
arr[:, 2] = 1
arr = np.random.randint(1,17, (4,4))
arr1 = np.fill_diagonal(arr, 0)
print(arr1)

None


In [34]:
import numpy as np

# Create a 3x3 NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Replace diagonal elements with a value (e.g., 0)
np.fill_diagonal(arr, 0)

print(arr)

[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [39]:
ar = np.random.randint(1,17, (4,4))
np.fill_diagonal(ar, 0)
print(ar)

[[ 0  5  3  9]
 [16  0 16  7]
 [ 2  4  0  5]
 [10  2 10  0]]


In [55]:
arr = np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [53]:
# 3rd to 5th rows and 2nd to 4th columns
arr[2:5, 1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [60]:
arr = np.random.rand(5,5)
arr

array([[0.57884874, 0.79744775, 0.66779429, 0.98099806, 0.06511674],
       [0.20728326, 0.09344949, 0.82990998, 0.69897967, 0.2477586 ],
       [0.37034993, 0.14910151, 0.26893536, 0.29909391, 0.37717212],
       [0.35488725, 0.54934921, 0.65631337, 0.31337527, 0.32060064],
       [0.64759336, 0.44494565, 0.87361985, 0.63494518, 0.25728211]])

In [73]:
top_row = arr[0,:]
bottom_row = arr[-1,:]
left_col = arr[1:-1, 0]
right_col = arr[1:-1, -1]
np.concat([top_row, right_col, bottom_row[::-1], left_col[::-1]])

array([0.57884874, 0.79744775, 0.66779429, 0.98099806, 0.06511674,
       0.2477586 , 0.37717212, 0.32060064, 0.25728211, 0.63494518,
       0.87361985, 0.44494565, 0.64759336, 0.35488725, 0.37034993,
       0.20728326])

In [67]:
arr[1:-1, 0]

array([0.20728326, 0.37034993, 0.35488725])

In [68]:
arr[1:-1, -1]

array([0.2477586 , 0.37717212, 0.32060064])

In [75]:
arr = np.random.rand(3,4)
arr

array([[0.79378133, 0.88117442, 0.13028115, 0.93911155],
       [0.18879301, 0.41093542, 0.1853425 , 0.14055122],
       [0.37686755, 0.32210803, 0.36205436, 0.17036937]])

In [81]:
first_row = arr[0,:]
last_row = arr[-1, :]
first_col = arr[:, 0]
last_col = arr[:, -1]

first_row * last_row
first_row / last_row
first_row - last_row
first_row + last_row

array([1.17064888, 1.20328245, 0.4923355 , 1.10948092])

In [82]:
first_col * last_col
first_col / last_col
first_col - last_col
first_col + last_col

array([1.73289288, 0.32934424, 0.54723692])

In [83]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [102]:
arr = np.random.rand(5,5)
np.mean(arr)
# np.std(arr)
# np.var(arr)
# np.median(arr)

np.float64(0.45982141208452176)

In [103]:
arr = np.random.randint(1,10, (3,3))
std = np.std(arr)
var = np.var(arr)
mean = np.mean(arr)

In [104]:
normalized = (arr - mean) / std
normalized

array([[ 1.94145069, -0.13867505, -0.97072534],
       [-1.38675049,  0.2773501 ,  1.10940039],
       [-0.13867505,  0.2773501 , -0.97072534]])

In [110]:
arr = np.random.rand(3,3)
arr_1d = np.array([1,3,5])
arr + arr_1d

array([[1.45700769, 3.33203094, 5.61634446],
       [1.82630116, 3.92609183, 5.74789829],
       [1.69652009, 3.15521324, 5.37836883]])

In [115]:
arr + arr_1d
arr * arr_1d
arr / arr_1d
arr - arr_1d

array([[-0.54299231, -2.66796906, -4.38365554],
       [-0.17369884, -2.07390817, -4.25210171],
       [-0.30347991, -2.84478676, -4.62163117]])

In [121]:
arr = np.random.randint(1,10, (3,3))
inverse = np.linalg.inv(arr)
determinant = np.linalg.det(arr)
eigenvalues, eigenvectors = np.linalg.eig(arr)
print(eigenvalues)
print(determinant)
print(inverse)

[15.08309326 -0.78367695 -3.29941631]
38.99999999999999
[[-1.07692308  0.69230769  1.15384615]
 [ 0.84615385 -0.61538462 -0.69230769]
 [-0.25641026  0.30769231  0.17948718]]


In [122]:
inverse * arr

array([[-4.30769231,  6.23076923, 10.38461538],
       [ 0.84615385, -2.46153846, -6.23076923],
       [-1.02564103,  1.84615385,  0.53846154]])

In [124]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [126]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [128]:
np.random.randint(1,10, (3,3)).reshape(1,9)

array([[2, 4, 7, 8, 6, 8, 2, 6, 9]])

In [131]:
np.random.randint(1,26,(5,5)).flatten().reshape(5,5)

array([[ 1,  7,  6, 21, 23],
       [18, 21, 20,  2, 23],
       [12, 21, 19, 15, 22],
       [ 2,  2, 16,  9, 14],
       [15, 11, 19,  5, 25]])

In [133]:
arr = np.random.rand(5,5)
arr

array([[0.86343268, 0.82433578, 0.02610914, 0.99479208, 0.17865251],
       [0.4007382 , 0.90538506, 0.95981418, 0.95740048, 0.81844716],
       [0.66773764, 0.29665715, 0.82263739, 0.35250566, 0.83190419],
       [0.52206659, 0.49319613, 0.62344742, 0.32897035, 0.02217182],
       [0.8959749 , 0.14554842, 0.71041791, 0.18725907, 0.12864041]])

In [135]:
row_corners = [0, 0, 4, 4]
col_corners = [0, 4, 0, 4]
arr[row_corners, col_corners]

array([0.86343268, 0.17865251, 0.8959749 , 0.12864041])

In [138]:
arr[arr > 0.5]

array([0.86343268, 0.82433578, 0.99479208, 0.90538506, 0.95981418,
       0.95740048, 0.81844716, 0.66773764, 0.82263739, 0.83190419,
       0.52206659, 0.62344742, 0.8959749 , 0.71041791])

In [140]:
dtype = [('name','U10'), ('age','i4'), ('weight','f4')]

data = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 22, 70.2),
    ('Charlie', 30, 68.3),
    ('Diana', 23, 60.4)

], dtype=dtype)

np.sort(data, order='age')

array([('Bob', 22, 70.2), ('Diana', 23, 60.4), ('Alice', 25, 55.5),
       ('Charlie', 30, 68.3)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [146]:
dtype = [('x','i4'), ('y','i4')]

data = np.array([
    (1, 2),
    (4, 6),
    (7, 8)
],dtype=dtype
)

data.dtype

dtype([('x', '<i4'), ('y', '<i4')])

In [144]:
import numpy as np

# Define the structured array dtype
dtype = [('x', 'i4'), ('y', 'i4')]

# Create the structured array with some points
data = np.array([(1, 2), (4, 6), (7, 8)], dtype=dtype)

print("Original Data (Points):")
print(data)

# Extract the 'x' and 'y' fields
x_coords = data['x']
y_coords = data['y']

# Compute the Euclidean distances between each pair of points
n = len(data)
distances = np.zeros((n, n))  # Create an empty matrix to store distances
for i in range(n):
    for j in range(n):
        # Compute distance between points i and j
        distances[i, j] = np.sqrt((x_coords[i] - x_coords[j])**2 + (y_coords[i] - y_coords[j])**2)

print("\nEuclidean Distance Matrix:")
print(distances)

Original Data (Points):
[(1, 2) (4, 6) (7, 8)]

Euclidean Distance Matrix:
[[0.         5.         8.48528137]
 [5.         0.         3.60555128]
 [8.48528137 3.60555128 0.        ]]
